In [3]:
import torch
print(f"Current Running Version : {torch.__version__}")

Current Running Version : 2.12.1


### 1. Create Tensors


In [12]:
# 1. Creating a tensor with empty function
tensor = torch.empty(3,2)
print(f"Type of Tensor : {tensor.dtype}")
print(f"Type of data structure : {type(tensor)}")
print(tensor)

Type of Tensor : torch.float32
Type of data structure : <class 'torch.Tensor'>
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [17]:
# 2. Creating a tensor with zero function

zero_tensor = torch.zeros(3,3)
print(f"Type of data in tensor : {tensor.dtype}")
print(zero_tensor)

Type of data in tensor : torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [19]:
# 3. Creating a tensor with ones function

ones_tensor = torch.ones(4,5)
print(ones_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [45]:
# 4. Creating a tensor with random function

rand_tensor = torch.rand(3,4)
print(rand_tensor)

tensor([[0.7111, 0.5400, 0.4944, 0.3959],
        [0.2533, 0.3334, 0.3186, 0.0288],
        [0.7021, 0.1448, 0.9781, 0.9261]])


In [ ]:
# 5. Creating a tensor with seed function for reproducibility

torch.manual_seed(56)
rand_tensor_with_seed = torch.rand(2,3)
print(rand_tensor_with_seed)

tensor([[0.9531, 0.5607, 0.3535],
        [0.9455, 0.4676, 0.7281]])


In [ ]:
# 6. Creating a custom tensor

custom_tensor = torch.tensor([
    [1,2,3],
    [4,5,6]
])

print(f"Dimension of custom tensor : {custom_tensor.shape}")
print(custom_tensor)


Dimension of custom tensor : torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [63]:
# Other Methods to create tensors

## 1. Using arange
print("Tensor created using arange method: ")
tensor_arange = torch.arange(0,10,1) # start, stop, steps
print(tensor_arange,"\n")

## 2. Using linspace (produce evenly spaced values)
print("Tensor created using linspace method: ")
tensor_linspace = torch.linspace(0,10,4) # start, stop, number of elements
print(tensor_linspace,"\n")

## 3. Using eye (creates Identity matrix of n x n)
print("Tensor created using eye method :")
tensor_eye = torch.eye(5) # creates an identity matrix of size 5x5
print(tensor_eye,"\n")

## 4. Using full
print("Tensor created using full method: ")
tensor_full = torch.full((3,3),5) # creates a 3X3 tensor filled with the value 5
print(tensor_full,"\n")

Tensor created using arange method: 
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 

Tensor created using linspace method: 
tensor([ 0.0000,  3.3333,  6.6667, 10.0000]) 

Tensor created using eye method :
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]) 

Tensor created using full method: 
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]) 



### 2. Tensors Shapes

In [68]:
x = torch.tensor([
    [1,2,3],
    [1,4,6]
])

print("Shape of x: ",x.shape) # prints shape of tensor x

## Making a tensor with same shape

y = torch.zeros_like(x)
print("Tensor y created using zeros_like method: \n",y)

z = torch.ones_like(x)
print("Tensor z created using ones_like method: \n",z)

z1 = torch.rand_like(x, dtype=torch.float32) # creates a random tensor with the same shape as x
print("Tensor z1 created using rand_like method with dtype torch.float32: \n",z1)


Shape of x:  torch.Size([2, 3])
Tensor y created using zeros_like method: 
 tensor([[0, 0, 0],
        [0, 0, 0]])
Tensor z created using ones_like method: 
 tensor([[1, 1, 1],
        [1, 1, 1]])
Tensor z1 created using rand_like method with dtype torch.float32: 
 tensor([[0.2759, 0.4734, 0.7383],
        [0.5281, 0.2217, 0.7745]])


### 3. Tensor Data Types

In [ ]:
# Assign Data type to tensor
x = torch.tensor([1,2,3], dtype=torch.int8)
print(f"Data type of tensor x: {x.dtype}")

# Convert data type of tensor
y = torch.tensor([1.0,2.0,3.0])
z = y.type(torch.float64) # y.to(torch.float64)
print(f"Converted data type of tensor y to float64: \n",z)

Data type of tensor x: torch.int8
Converted data type of tensor y to float64: 
 tensor([1., 2., 3.], dtype=torch.float64)


## Data Types in PyTorch

| **Data Type** | **Dtype** | **Description** | **Common Use Cases** |
|---|---|---|---|
| **32-bit Floating Point** | `torch.float32` | Default floating-point dtype with a good balance between precision, speed, and memory usage. | Model weights, activations, loss calculations, general deep learning |
| **64-bit Floating Point** | `torch.float64` | Double-precision floating point with higher numerical accuracy and greater memory usage. | Scientific computing, numerical analysis, debugging |
| **16-bit Floating Point** | `torch.float16` | Half-precision floating point that reduces memory usage and can accelerate supported GPU operations. | Mixed-precision training, GPU inference |
| **BFloat16** | `torch.bfloat16` | 16-bit format with the same exponent range as `float32` but lower precision. | Large-model training, mixed precision, TPUs, supported CPUs and GPUs |
| **Float8 E4M3** | `torch.float8_e4m3fn` | 8-bit floating-point format optimized for relatively higher precision within float8 formats. | Experimental low-precision training and inference |
| **Float8 E5M2** | `torch.float8_e5m2` | 8-bit floating-point format with a wider range but lower precision than E4M3. | Experimental training, gradients, large-scale model workloads |
| **8-bit Signed Integer** | `torch.int8` | Signed integer with values from -128 to 127. | Quantized models, compact integer data |
| **16-bit Signed Integer** | `torch.int16` | Signed 16-bit integer for integer calculations requiring a larger range than `int8`. | Signal processing, compact numerical data |
| **32-bit Signed Integer** | `torch.int32` | Signed 32-bit integer. | Integer calculations, some indexing operations, interoperability |
| **64-bit Signed Integer** | `torch.int64` | Signed 64-bit integer, also known as `torch.long`. | Tensor indices, class labels, counters, integer calculations |
| **8-bit Unsigned Integer** | `torch.uint8` | Unsigned integer with values from 0 to 255. | Legacy image data, byte data, masks |
| **16-bit Unsigned Integer** | `torch.uint16` | Unsigned 16-bit integer. Availability and operator support depend on the PyTorch version. | Compact non-negative data, specialized applications |
| **32-bit Unsigned Integer** | `torch.uint32` | Unsigned 32-bit integer. Availability and operator support depend on the PyTorch version. | Specialized integer data and interoperability |
| **64-bit Unsigned Integer** | `torch.uint64` | Unsigned 64-bit integer. Availability and operator support depend on the PyTorch version. | Large non-negative integer values, specialized applications |
| **Boolean** | `torch.bool` | Stores `True` or `False` values. | Masks, comparisons, conditional selection |
| **Complex 64** | `torch.complex64` | Complex numbers with 32-bit real and imaginary components. | Signal processing, Fourier transforms, scientific computing |
| **Complex 128** | `torch.complex128` | Complex numbers with 64-bit real and imaginary components. | High-precision scientific and signal-processing calculations |
| **Quantized Signed Integer** | `torch.qint8` | Quantized signed 8-bit representation interpreted using a scale and zero point. | Quantized model weights and inference |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit representation interpreted using a scale and zero point. | Quantized activations and inference |
| **Quantized 32-bit Integer** | `torch.qint32` | Quantized 32-bit signed integer representation. | Certain quantized layers and accumulators |





> **Note:** Dtype availability and operator support depend on the installed PyTorch version and hardware backend. Quantized dtypes such as `torch.qint8` and `torch.quint8` require quantization metadata, including a scale and zero point; they are not ordinary tensor dtypes for most `torch.tensor()` calls.

### 4. Mathematical Operations on tensors

#### 1. Scaler Operation

In [72]:
x = torch.tensor([
    [1,2],
    [1,4]
])

# 1.Addition of a scalar to all elements in the tensor
y = x + 3
print(y)

# 2. subtraction of a scalar from all elements in the tensor
z = x - 3
print(z)

# 3. Multiplication of a scalar with all elements in the tensor
w = x * 3
print(w)

# 4. Division of a scalar by all elements in the tensor
v = x / 3
print(v)

# 5. Mode 
print(((x * 100)// 2)% 2)

# 6. Power
print(x**2)

tensor([[4, 5],
        [4, 7]])
tensor([[-2, -1],
        [-2,  1]])
tensor([[ 3,  6],
        [ 3, 12]])
tensor([[0.3333, 0.6667],
        [0.3333, 1.3333]])
tensor([[0, 0],
        [0, 0]])
tensor([[ 1,  4],
        [ 1, 16]])


#### 2. Element Wise Operation

In [76]:
torch.manual_seed(45)
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1869, 0.9613, 0.6834],
        [0.8988, 0.0505, 0.5555]])
tensor([[0.7861, 0.0566, 0.7842],
        [0.1480, 0.0388, 0.1037]])


In [82]:
# 1. Addition of two tensors
print("Addition : \n",a+b)

# 2. Subtraction of two tensors
print("Subtraction : \n",a-b)

# 3. Multiplication of two tensors
print("Multiplication : \n",a*b)

# 4. Division of two tensors
print("Division : \n",a/b)

# 5. Modulo operation between two tensors
print("Modulo Operation : \n",a%b)

# 6. Power operation between two tensors
print("Power Operation : \n",a**b)

Addition : 
 tensor([[0.9731, 1.0180, 1.4676],
        [1.0468, 0.0893, 0.6592]])
Subtraction : 
 tensor([[-0.5992,  0.9047, -0.1007],
        [ 0.7508,  0.0117,  0.4517]])
Multiplication : 
 tensor([[0.1470, 0.0544, 0.5360],
        [0.1330, 0.0020, 0.0576]])
Division : 
 tensor([[ 0.2378, 16.9778,  0.8715],
        [ 6.0736,  1.3004,  5.3545]])
Modulo Operation : 
 tensor([[0.1869, 0.0554, 0.6834],
        [0.0109, 0.0117, 0.0368]])
Power Operation : 
 tensor([[0.2676, 0.9978, 0.7420],
        [0.9843, 0.8905, 0.9408]])


#### 3. Operation on single tensors

In [152]:
x = torch.tensor([-2,-1,0,1,2])
y = torch.tensor([1.0, 2.9, 3.5, 4.7, 5.1]) 

# 1. Absolute value of a tensor
print("Absolute Value : \n",torch.abs(x))

# 2. Square root of a tensor
print("Square Root : \n",torch.sqrt(x))

# 3. Exponential of a tensor
print("Exponential : \n",torch.exp(x))

# 4. Logarithm of a tensor
print("Logarithm : \n",torch.log(x))

# 5. Round off of a tensor
print("Round Off : \n",torch.round(x))

# 6. Negative of a tensor
print("Negative : \n",torch.neg(x))

# 7. Maximum value in a tensor
print("Maximum Value : \n",torch.max(x,y))

# 8. ceiling of a tensor
print("Ceiling : \n",torch.ceil(y))

# 9. floor of a tensor
print("Floor : \n",torch.floor(y))

# 10. clam of a tensor
print("Clamp : \n",torch.clamp(y,0,5)) # tensor, min, max

# 11. sigmoid for each element in a tensor
print("Sigmoid : \n",torch.sigmoid(y)) # sigmoid function

# 12. tanh for each element in a tensor
print("Tanh : \n",torch.tanh(y)) # tanh function

# 13. softmax for each element in a tensor
print("Softmax : \n",torch.softmax(y, dim=0)) # softmax function across row 

# 14. relu for each element in a tensor
print("ReLU : \n",torch.relu(y)) # relu function


Absolute Value : 
 tensor([2, 1, 0, 1, 2])
Square Root : 
 tensor([   nan,    nan, 0.0000, 1.0000, 1.4142])
Exponential : 
 tensor([0.1353, 0.3679, 1.0000, 2.7183, 7.3891])
Logarithm : 
 tensor([   nan,    nan,   -inf, 0.0000, 0.6931])
Round Off : 
 tensor([-2, -1,  0,  1,  2])
Negative : 
 tensor([ 2,  1,  0, -1, -2])
Maximum Value : 
 tensor([1.0000, 2.9000, 3.5000, 4.7000, 5.1000])
Ceiling : 
 tensor([1., 3., 4., 5., 6.])
Floor : 
 tensor([1., 2., 3., 4., 5.])
Clamp : 
 tensor([1.0000, 2.9000, 3.5000, 4.7000, 5.0000])
Sigmoid : 
 tensor([0.7311, 0.9478, 0.9707, 0.9910, 0.9939])
Tanh : 
 tensor([0.7616, 0.9940, 0.9982, 0.9998, 0.9999])
Softmax : 
 tensor([0.0083, 0.0554, 0.1010, 0.3352, 0.5001])
ReLU : 
 tensor([1.0000, 2.9000, 3.5000, 4.7000, 5.1000])


#### 4. Reduction Operation

In [103]:
# Tensor with random int with specific range and shape
torch.manual_seed(4)
x = torch.randint(size=(3,2), low=0, high=10)
print("Tensor : \n",x)

Tensor : 
 tensor([[0, 4],
        [1, 3],
        [9, 6]])


##### Sum

In [107]:
# 1. Sum of all elements in a tensor
print(f"Sum of all element of tensor x : {torch.sum(x)}")

# 2. Sum along axis 1 (row wise sum)
print(f"Sum along axis 1 (row wise sum) : \n",torch.sum(x, dim=1))

# 3. Sum along axis 0 (column wise sum)
print(f"Sum along axis 0 (column wise sum) : \n",torch.sum(x,dim=0))


Sum of all element of tensor x : 23
Sum along axis 1 (row wise sum) : 
 tensor([ 4,  4, 15])
Sum along axis 0 (column wise sum) : 
 tensor([10, 13])


##### Mean

In [110]:
y = torch.randint(size=(2,4), low=0, high=10, dtype=torch.float32)
print("Tensor : \n",y)

# 1. Mean of all elements in a tensor
print(f"Mean of all element of tensor y : {torch.mean(y)}","\n")

# 2. Mean along axis 1 (row wise mean)
print(f"Mean along axis 1 (row wise mean) : \n",torch.mean(y, dim=1))

# 3. Mean along axis 0 (column wise mean)
print(f"Mean along axis 0 (column wise mean) : \n",torch.mean(y,dim=0))

Tensor : 
 tensor([[8., 4., 2., 4.],
        [1., 2., 9., 7.]])
Mean of all element of tensor y : 4.625 

Mean along axis 1 (row wise mean) : 
 tensor([4.5000, 4.7500])
Mean along axis 0 (column wise mean) : 
 tensor([4.5000, 3.0000, 5.5000, 5.5000])


##### Median

In [116]:
torch.manual_seed(45)
y = torch.randint(size=(2,4), low=0, high=10, dtype=torch.float32)
print("Tensor : \n",y,"\n")

# 1. Median of all elements in a tensor
print(f"Median of all element of tensor y : {torch.median(y)}","\n")

# 2. Median along axis 1 (row wise median)
print(f"Median along axis 1 (row wise median) : \n",torch.median(y, dim=1),"\n")

# 3. Median along axis 0 (column wise median)
print(f"Median along axis 0 (column wise median) : \n",torch.median(y, dim=0),"\n")

Tensor : 
 tensor([[7., 6., 1., 8.],
        [4., 9., 7., 3.]]) 

Median of all element of tensor y : 6.0 

Median along axis 1 (row wise median) : 
 torch.return_types.median(
values=tensor([6., 4.]),
indices=tensor([1, 0])) 

Median along axis 0 (column wise median) : 
 torch.return_types.median(
values=tensor([4., 6., 1., 3.]),
indices=tensor([1, 0, 0, 1])) 



#### Min and Max

In [120]:
torch.manual_seed(45)
y = torch.randint(size=(2,4), low=0, high=5, dtype=torch.float32)
print("Tensor : \n",y,"\n")

# Min/Max of all elements in a tensor
print(f"Min: {torch.min(y)} | Max: {torch.max(y)}")

Tensor : 
 tensor([[2., 1., 1., 3.],
        [4., 4., 2., 3.]]) 

Min: 1.0 | Max: 4.0


##### Product

In [121]:
print(f"Product of all element of tensor y : {torch.prod(y)}")

Product of all element of tensor y : 576.0


##### Standard Deviation

In [122]:
print(f"Standard Deviation of all element of tensor y : {torch.std(y)}")

Standard Deviation of all element of tensor y : 1.1952285766601562


##### Variance

In [123]:
print(f"Variance of all element of tensor y : {torch.var(y)}")

Variance of all element of tensor y : 1.4285714626312256


##### argmax

In [126]:
print(y)
print("Argmax: ",torch.argmax(y)) # returns the index of maximum value in a tensor

tensor([[2., 1., 1., 3.],
        [4., 4., 2., 3.]])
Argmax:  tensor(4)


##### argmin

In [127]:
print(y)
print("Argmin: ",torch.argmin(y)) # returns the index of maximum value in a tensor

tensor([[2., 1., 1., 3.],
        [4., 4., 2., 3.]])
Argmin:  tensor(1)


#### 5. Matrix Operations

In [134]:
x = torch.randint(size=(2,4), low=0, high=5, dtype=torch.float32)
y = torch.randint(size=(4,2), low=0, high=5, dtype=torch.float32)
print("X: \n", x)
print("Y: \n",y)

# Matrix Multiplication
print(f"Matrix Multiplication : {torch.matmul(x,y)}")

X: 
 tensor([[1., 4., 1., 3.],
        [4., 2., 2., 4.]])
Y: 
 tensor([[3., 0.],
        [3., 4.],
        [2., 2.],
        [4., 1.]])
Matrix Multiplication : tensor([[29., 21.],
        [38., 16.]])


In [135]:
# Dot product of two vectors 
v = torch.tensor([1,2,3])
u = torch.tensor([3,4,5])

print(f"Dot Product of v and u: {torch.dot(v,u)}")

Dot Product of v and u: 26


In [137]:
# Transpose of a matrix

print("Transpose of x: \n",torch.transpose(x,0,1)) # transpose along axis 0 (rows) and 1 (columns)

Transpose of x: 
 tensor([[1., 4.],
        [4., 2.],
        [1., 2.],
        [3., 4.]])


In [141]:
# Determinant of a matrix
x = torch.eye(3)
print(f"Determinant of x: {torch.det(x)}") # Determinant of a square matrix

Determinant of x: 1.0


In [142]:
# Inverse of a matrix
x = torch.eye(3)
print(f"Inverse of x: {torch.inverse(x)}") # Inverse of a square matrix

Inverse of x: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### 6. Comparison Operation

In [145]:
torch.manual_seed(45)
x = torch.randint(size=(2,4), low=0, high=5, dtype=torch.float32)
y = torch.randint(size=(2,4), low=0, high=5, dtype=torch.float32)

print("X: \n", x)
print("Y: \n",y)

X: 
 tensor([[2., 1., 1., 3.],
        [4., 4., 2., 3.]])
Y: 
 tensor([[3., 0., 2., 1.],
        [4., 3., 1., 3.]])


In [ ]:
# Element Wise Comparison 

# 1. Greater than (>)
print("Greater than X and Y: \n",torch.gt(x,y),"\n") 

# 2. Less than (<)
print("Less than X and Y: \n",torch.lt(x,y),"\n")

# 3. Equal to (=)
print("Equal to X and Y: \n",torch.eq(x,y),"\n")

# 4. Not equal to (!=)
print("Not equal to X and Y: \n",torch.ne(x,y),"\n")


Greater than X and Y: 
 tensor([[False,  True, False,  True],
        [False,  True,  True, False]]) 

Less than X and Y: 
 tensor([[ True, False,  True, False],
        [False, False, False, False]]) 

Equal to X and Y: 
 tensor([[False, False, False, False],
        [ True, False, False,  True]]) 

Not equal to X and Y: 
 tensor([[ True,  True,  True,  True],
        [False,  True,  True, False]]) 



### 7. Inplace Operation

In [ ]:
torch.manual_seed(45)

x = torch.randint(size=(2,4), low=0, high=5, dtype=torch.float32)
y = torch.randint(size=(2,4), low=0, high=5, dtype=torch.float32)

# 1.To add without making new tensor
print("Addition of X and Y: \n",x.add_(y), "\n") # Stores the new tensor to x

# 2. To multiply without making new tensor
print("Multiplication of X and Y: \n",x.mul_(y), "\n") # Stores the new tensor to x

# x.function_() represent inplace operation

Addition of X and Y: 
 tensor([[5., 1., 3., 4.],
        [8., 7., 3., 6.]]) 

Multiplication of X and Y: 
 tensor([[15.,  0.,  6.,  4.],
        [32., 21.,  3., 18.]]) 



#### 8. Copy a Tensor

In [160]:
torch.manual_seed(45)
x = torch.randint(size=(2,4), low=0, high=5, dtype=torch.float32)

# If we assign this tensor to new variable they both we point to the same location in memory i.e change in one tensor will reflect on other as well
y = x
if id(x) == id(y):
    print("Both are pointing to same location in memory")
else:
    print("Both are not pointing to same location in memory")

# so to copy a tensor we use clone(), it creates a new tensor with the same data as the original tensor.
z = x.clone()
if id(x) == id(z):
    print("Both are pointing to same location in memory")
else:
    print("Both are not pointing to same location in memory")


Both are pointing to same location in memory
Both are not pointing to same location in memory


#### 9. Tensor Operations on GPU

In [9]:
if torch.backends.mps.is_available():
    
    print("GPU is available ! (via MPS)")
    device = torch.device("mps")
    
elif torch.cuda.is_available():
    
    print("GPU is available!! (via CUDA)")
    device = torch.device("cuda")
    print(f"Device Name : {torch.cuda.get_device_name()}")
    
else:
    
    print("No GPU found, using CPU")
    device = torch.device("cpu")

print(f"Active device: {device}")
print(torch.backends.mps.is_built())



GPU is available ! (via MPS)
Active device: mps
True


### NOTE:  whenever  build tensors/models, move them to that device explicitly:

```
model = model.to(device)
x = x.to(device)
```

In [10]:
# Creating a tensor on GPU
tensor_on_gpu = torch.tensor([1.0, 2.0, 3.0], device=device)
print(tensor_on_gpu)

tensor([1., 2., 3.], device='mps:0')


In [11]:
# Move Existing Tensors to GPU
torch.manual_seed(45)

# These Tensors are on CPU by default
x = torch.randint(size=(2, 3),low=0,high=100)
y = torch.randint(size=(2,3),low=0,high=100)

# Move tensors to GPU
x_gpu = x.to(device)
y_gpu = y.to(device)

print(f"Tensor X on GPU : {x_gpu}")
print(f"Tensor Y on GPU : {y_gpu}")

# Any Operation will be performed on the GPU
z = torch.add(x_gpu, y_gpu)
print(z)

Tensor X on GPU : tensor([[ 7, 46, 11],
        [28, 44, 19]], device='mps:0')
Tensor Y on GPU : tensor([[57, 93, 23],
        [ 0, 77, 76]], device='mps:0')
tensor([[ 64, 139,  34],
        [ 28, 121,  95]], device='mps:0')


### 10. Time difference b/w CPU and GPU computation

In [19]:
import time
torch.manual_seed(45)

# Define Size of matrix
size = 20000

# Create a random matrix on CPU
x_cpu = torch.rand(size, size)
y_cpu = torch.rand(size, size)

# Time Measurement for CPU Operation
start_time = time.time()
result_cpu = torch.matmul(x_cpu, y_cpu)
cpu_time = time.time() - start_time

print(f"CPU Matrix Multiplication took {cpu_time:.4f} seconds")


CPU Matrix Multiplication took 11.4091 seconds


In [20]:
# Move to GPU
x_gpu = x_cpu.to(device)
y_gpu = y_cpu.to(device)

# Time Measurement for GPU Operation
start_time = time.time()
result_gpu = torch.matmul(x_gpu, y_gpu)
gpu_time = time.time() - start_time
print(f"GPU Matrix Multiplication took {gpu_time:.4f} seconds")


# Compare result
print(f"Speed Up: {cpu_time / gpu_time:.2f} times faster on GPU")

GPU Matrix Multiplication took 0.0240 seconds
Speed Up: 476.06 times faster on GPU


### 11. Reshaping Tensor

In [33]:
torch.manual_seed(45)
x = torch.ones(3,2)
print(x.shape)

torch.Size([3, 2])


In [34]:
# Reshape the tensor to a single row
x = x.reshape(1,6) 
print(x.shape)

torch.Size([1, 6])


In [44]:
# Flatten the tensor to a single column
flat = x.flatten() # This is equivalent to x.view(-1, 1)
print(flat.shape)
print(flat,"\n")

column = x.flatten().reshape(-1,1)
print(column.shape)
column

torch.Size([6])
tensor([1., 1., 1., 1., 1., 1.]) 

torch.Size([6, 1])


tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [46]:
# Permute
x = torch.rand(3,2,4)
print(x.shape)

permuted = x.permute(0,2,1) # This will swap the first and third dimensions
print(permuted.shape)

torch.Size([3, 2, 4])
torch.Size([3, 4, 2])


In [48]:
# Unsqueeze
image = torch.rand(256, 256, 3)
print(image.shape)

print(f"Unsqueezed image shape: {image.unsqueeze(0).shape}")

torch.Size([256, 256, 3])
Unsqueezed image shape: torch.Size([1, 256, 256, 3])


In [49]:
# Squeeze 
print(f"Squeezed image shape: {image.squeeze(1).shape}")

Squeezed image shape: torch.Size([256, 256, 3])


### 12. NumPy and PyTorch

In [54]:
import numpy as np

a = torch.tensor([2,3,4])
b = np.array([2,3,34])

# Convert tensor to numpy array
a = a.numpy()
print(type(a))

# Convert Numpy to tensor 
b = torch.from_numpy(b)
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
